name: Testing

on: [push, workflow_dispatch]

jobs:
  tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: cp .env.example .env
      - name: Add testing key
        run: echo DETA_PROJECT_KEY=${{ secrets.DETA_TEST_KEY }} >> .env
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Building the image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ secrets.IMAGE_TAG }}:latest
          cache-from: type=registry,ref=${{ secrets.IMAGE_TAG }}:latest
      - name: Backend tests
        run: make tag=${{ secrets.IMAGE_TAG }} test_exit=1 _test
      - name: Linting
        run: make tag=${{ secrets.IMAGE_TAG }} test_exit=1 lint
