name: Testing

on: [push, workflow_dispatch]

jobs:
  tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: cp .env.example .env
      - name: Add testing key
        run: echo DETA_PROJECT_KEY=${{ secrets.DETA_TEST_KEY }} >> .env
      - name: Cache images
        run: docker pull ghcr.io/monochromecms/monochrome-api-deta:latest
      - name: Building the image
        run: make build
      - name: Backend tests
        run: make test_exit=1 _test
      - name: Linting
        run: make test_exit=1 lint
